// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using little_heart_bot_3.Data;

#nullable disable

namespace little_heart_bot_3.Migrations
{
    [DbContext(typeof(LittleHeartDbContext))]
    partial class LittleHeartDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("little_heart_bot_3.Data.Models.BotModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("AppStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("app_status")
                        .HasComment("0 正常, -1 冷却中");

                    b.Property<string>("Cookie")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(2000)")
                        .HasDefaultValue("")
                        .HasColumnName("cookie")
                        .HasComment("成为小心心bot的用户的cookie");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_time")
                        .HasDefaultValueSql("NOW(6)");

                    b.Property<string>("Csrf")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(32)")
                        .HasDefaultValue("")
                        .HasColumnName("csrf")
                        .HasComment("成为小心心bot的用户的csrf");

                    b.Property<string>("DevId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(36)")
                        .HasDefaultValue("")
                        .HasColumnName("dev_id")
                        .HasComment("成为小心心bot的用户的dev_id");

                    b.Property<int>("ReceiveStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("receive_status")
                        .HasComment("0 正常, -1 冷却中");

                    b.Property<int>("SendStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("send_status")
                        .HasComment("0 正常, -1 冷却中, -2 禁言");

                    b.Property<long>("Uid")
                        .HasColumnType("bigint")
                        .HasColumnName("uid")
                        .HasComment("成为小心心bot的用户的uid");

                    b.Property<DateTime>("UpdateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("update_time")
                        .HasDefaultValueSql("NOW(6)");

                    b.HasKey("Id");

                    b.HasIndex("Uid")
                        .IsUnique();

                    b.ToTable("bot_table", (string)null);
                });

            modelBuilder.Entity("little_heart_bot_3.Data.Models.MessageModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("code");

                    b.Property<bool>("Completed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("completed")
                        .HasComment("弹幕是否已发送");

                    b.Property<string>("Content")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("content")
                        .HasComment("弹幕的内容");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_time")
                        .HasDefaultValueSql("NOW(6)");

                    b.Property<string>("Response")
                        .HasColumnType("json")
                        .HasColumnName("response");

                    b.Property<long>("RoomId")
                        .HasColumnType("bigint")
                        .HasColumnName("room_id");

                    b.Property<string>("TargetName")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("target_name");

                    b.Property<long>("TargetUid")
                        .HasColumnType("bigint")
                        .HasColumnName("target_uid");

                    b.Property<long>("Uid")
                        .HasColumnType("bigint")
                        .HasColumnName("uid")
                        .HasComment("用户的uid");

                    b.Property<DateTime>("UpdateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("update_time")
                        .HasDefaultValueSql("NOW(6)");

                    b.HasKey("Id");

                    b.HasIndex("Uid", "TargetUid")
                        .IsUnique();

                    b.ToTable("message_table", (string)null);
                });

            modelBuilder.Entity("little_heart_bot_3.Data.Models.TargetModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("Completed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("completed")
                        .HasComment("今日任务是否已完成");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_time")
                        .HasDefaultValueSql("NOW(6)");

                    b.Property<int>("Exp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("exp")
                        .HasComment("今日已获得的经验");

                    b.Property<long>("RoomId")
                        .HasColumnType("bigint")
                        .HasColumnName("room_id")
                        .HasComment("直播间的room_id");

                    b.Property<string>("TargetName")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("target_name")
                        .HasComment("直播间主播的名字");

                    b.Property<long>("TargetUid")
                        .HasColumnType("bigint")
                        .HasColumnName("target_uid")
                        .HasComment("直播间主播的uid");

                    b.Property<long>("Uid")
                        .HasColumnType("bigint")
                        .HasColumnName("uid")
                        .HasComment("用户的uid");

                    b.Property<DateTime>("UpdateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("update_time")
                        .HasDefaultValueSql("NOW(6)");

                    b.Property<int>("WatchedSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("watched_seconds")
                        .HasComment("今日已观看直播的时长");

                    b.HasKey("Id");

                    b.HasIndex("Uid", "TargetUid")
                        .IsUnique();

                    b.ToTable("target_table", (string)null);
                });

            modelBuilder.Entity("little_heart_bot_3.Data.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("Completed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("completed")
                        .HasComment("今日的任务是否已完成");

                    b.Property<int>("ConfigNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("config_num")
                        .HasComment("今日查了多少次配置");

                    b.Property<long>("ConfigTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("config_timestamp")
                        .HasComment("上一次查询配置的时间戳");

                    b.Property<string>("Cookie")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(2000)")
                        .HasDefaultValue("")
                        .HasColumnName("cookie");

                    b.Property<int>("CookieStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("cookie_status")
                        .HasComment("0 未验证, 1 正常, -1 异常");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_time")
                        .HasDefaultValueSql("NOW(6)");

                    b.Property<string>("Csrf")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(32)")
                        .HasDefaultValue("")
                        .HasColumnName("csrf");

                    b.Property<long>("ReadTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("read_timestamp")
                        .HasComment("上一条已读私信的时间戳，用于找出未读私信");

                    b.Property<long>("Uid")
                        .HasColumnType("bigint")
                        .HasColumnName("uid");

                    b.Property<DateTime>("UpdateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("update_time")
                        .HasDefaultValueSql("NOW(6)");

                    b.HasKey("Id");

                    b.ToTable("user_table", (string)null);
                });

            modelBuilder.Entity("little_heart_bot_3.Data.Models.MessageModel", b =>
                {
                    b.HasOne("little_heart_bot_3.Data.Models.UserModel", "UserModel")
                        .WithMany("Messages")
                        .HasForeignKey("Uid")
                        .HasPrincipalKey("Uid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserModel");
                });

            modelBuilder.Entity("little_heart_bot_3.Data.Models.TargetModel", b =>
                {
                    b.HasOne("little_heart_bot_3.Data.Models.UserModel", "UserModel")
                        .WithMany("Targets")
                        .HasForeignKey("Uid")
                        .HasPrincipalKey("Uid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserModel");
                });

            modelBuilder.Entity("little_heart_bot_3.Data.Models.UserModel", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Targets");
                });
#pragma warning restore 612, 618
        }
    }
}
